### ISSUE TITLE
Note: in Prio3, clients duplicate hints

### ISSUE THREAD

**Issue by hannahdaviscrypto** [cfrg/draft-irtf-cfrg-vdaf#114]
In Prio3, the client generates a "hint" for each aggregator to help derive the joint randomness. These hints need to be communicated to all aggregators in the start of preparation, so the sharding algorithm encodes the entire list into each input share. If there are s aggregators, the client's message length will be quadratic in s: s hints * s input shares. This seems fine for s=2, but if applications where s > 2 are targeted, we may want to consider other encodings.

**Comment by hannahdaviscrypto** [comment]
A possible alternative for s>2: VDAF already supports a "public share" that the leader broadcasts to all aggregators, and Prio3 currently leaves this empty. We could have clients encode the hints in the public share so they are only sent once by the client. If authentication of the hints is needed, the client could encode some part of its joint randomness within each input share as a confirmation, which would preserve linear communcation  in s between the client and leader.

**Comment by hannahdaviscrypto** [comment]
As I step away from my internship project, these are the two outstanding proposed changes for Prio3:

1. Put the joint randomness hints into the public share instead of duplicating them in the aggregators' input shares, for the reasons described above. Additional authentication is unnecessary because in DAP, the public share is authenticated by HPKE.
2. Follow every domain separation tag in a PRG call with a 1-byte domain separation value between 249 and 255. The existing domain separation tag performs domain separation between Prio3 and external uses of its PRG. In contrast, the new value separates domains between internal uses of the PRG in different parts of the scheme,. e.g., for generating joint vs query randomness. This value performs domain separation between the different uses of the PRG.

**Comment by cjpatton** [comment]
Solved by #121.
