### ISSUE TITLE
Performance and usability improvements for Poplar1

### ISSUE THREAD

**Issue by hannahdaviscrypto** [cfrg/draft-irtf-cfrg-vdaf#122]
The current Poplar1 algorithm requires two rounds of communication between the aggregators (leader and helpers) to verify that the client's input has the correct format. We may be able to reduce the number of rounds to 1 and the size of the messages in each round by replacing the malicious-secure sketching portion of the algorithm with a more lightweight MPC technique. This technique can also expand the set of supported formats from one-hot binary vectors to one-hot vectors with a small bound on the nonzero element.

**Comment by cjpatton** [comment]
This issue is basically about specifying Doplar, which we're not going to do in this document. (At least not for now.)
