### ISSUE TITLE
Sum of vectors with Prio3

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#124]
I think it would be useful to have a VDAF instantiation to sum vectors of integers. This has come up a few times in conversations as a useful primitive. We could define it with two parameters: the length of the vector in elements, and the bit width of each element, so that their range would be $[0, 2^{bits}-1)$. I presume that we'd be able to make similar improvements to proving time or proof size here as with the proposed [Prio3Aes128CountVec](https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/83), compared to running multiple independent `Prio3Aes128Sum` VDAF instances.

**Comment by cjpatton** [comment]
SGTM! Queued for the next draft.

**Comment by tgeoghegan** [comment]
This is [`Prio3Aes128SumVec`](https://github.com/divviup/libprio-rs/pull/420), right?

**Comment by cjpatton** [comment]
Yes. Question here: Are we OK with not landing this in VDAF-04? Since everyone who is using it in the foreseeable future is using libprio, there is not an immediate need to specify it here.

**Comment by tgeoghegan** [comment]
I think that's reasonable. Plus it'd be good to get some practical experience with it before we specify it.

**Comment by divergentdave** [comment]
From offline discussion: we plan to make the parallel sum gadget "chunk size" an explicit parameter of the VDAF. This choice avoids having to specify an integer square root algorithm, plus it's possible that using a chunk size a bit above or below the square root of the total arity may be more optimal. See previous discussion starting at https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/83#issuecomment-1523703307.

**Comment by divergentdave** [comment]
I was looking at the Prio3SumVec implementation currently in libprio-rs, to line it up with tactics from the BBCGGI19 paper, and I think we can further improve on its proof size. The validation circuit calculates $\sum_i {r^{i+1}m_i}$, where r is a joint randomness value, and m is the measurement, in √n chunks of size √n, where n is the total number of bits in the measurement vector. It does so using a parallel sum gadget on the sub-circuit $C(x, y)=x(x-1)y$, assigning $x_i=m_i$ and $y_i=r^{i+1}$. To be more precise, this is done by setting the additive share of $y_i$ on each aggregator to $r^{i+1}s^{-1}$, where s is the number of shares. While this works, it is not necessary to use a degree of the sub-circuit to perform this multiplication by the joint randomness value. It is known by all parties, and can included with an affine constant multiplication gate (for free). We just have to entangle it with the $x^2-x$ polynomial evaluation differently.

The alternate circuit structure I'm proposing can be equivalently thought of in two ways, either as an inner product, to efficiently compute a degree-two relation (see section 4.3 of BBCGGI19), or as an optimization of a parallel-sum circuit, (see section 4.4) where the sub-circuit is just the Mul gate. As before, the circuit will output $\sum_i {r^{i+1}m_i}$, and it will be split up into √n chunks of size √n. We let the sub-circuit be $C(x,y)=xy$, and then use affine gates to assign $x_i=r^{i-1}m_i$ and $y_i=m_i-1$. Note that the constant -1 will have to be split up between aggregators, either into 0 and -1, or into $-s^-1$ on each. This gets us the same circuit result, with a lower degree gadget polynomial, and thus shorter proofs. (Once this is done, it may be worth applying a similar optimization to the range check part of the Prio3Histogram circuit as well, now that we know we don't need to trade off a higher circuit degree for the more compact arrangement of wires and gadgets)

I think it would make the most sense to describe the optimization for parallel-sum circuits, and then use it on Mul, as it is more general, and we would only skip the linear algebra part of section 4.3 (which is not even necessary for SumVec, since the circuit is already in an inner product form).

**Comment by cjpatton** [comment]
This is an excellent idea! How do we generalize to vectors of integers in range `[0, 2^k)`, and not just bit-vectors?

**Comment by divergentdave** [comment]
> This is an excellent idea! How do we generalize to vectors of integers in range `[0, 2^k)`, and not just bit-vectors?

That mainly changes the encoding and decoding steps. (compared to the Prio3CountVec case) Encoding a vector of integers requires concatenating the bit-vector representation of each vector element, and decoding partitions the field vector in groups as long as the bit width, then does the powers-of-two weighted sum within each partition. At the validation circuit level, we're still checking that a vector of field elements are all either zero or one, so that part is unchanged.

**Comment by cjpatton** [comment]
Yes indeed. Let's do it.

**Comment by divergentdave** [comment]
Here's a notebook that demonstrates choosing an optimal parallel sum gadget chunk size for any given measurement size. Note that the optimal chunk size zigzags around the square root we RECOMMEND in the text. The second chart shows the resulting proof sizes.

https://gist.github.com/divergentdave/a89fccd6375d9ac3d03cf5571709862d

**Comment by cjpatton** [comment]
I think it's worth figuring out a way to convey this in an "implementation" note for the ParallelSum gadget.
