### ISSUE TITLE
Byte ordering of encoded bit strings

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#147]
There are two places where the document currently deals with encoding and decoding of bit strings, in IdpfPoplar's public share, which packs control bits, and the optional serialization of Poplar1's aggregation parameter, which contains many bit string prefixes packed together. In both cases, the encoding is phrased in terms of using `I2OSP` on an arbitrary precision integer. In the case of IDPF pubilc share correction word control bits, the integer is formed from the control bits in LSB-to-MSB order. In the case of Poplar1, the algorithm's measurement and aggregation parameter inputs are both defined as integers, ~~though it's apparent that the least significant bit is semantically first in this case as well~~. This serialization is confusing to the eye, and requires some extra effort from implementors to accommodate (typically, reversing the order of a byte array). I think we should switch the byte-endianness of these encodings to simplify implementations. It might be worthwhile to drop the arbitrary precision integer representation altogether, and instead describe the algorithms in terms of bit strings or boolean arrays.

As a concrete example, here's how twelve bits currently get encoded:

```
sage: binascii.hexlify(sagelib.idpf_poplar.IdpfPoplar.with_bits(6).encode_public_share([(b"", [Field2(0), Field2(1)], []), (b"", [Field2(1), Field2(0)], []), (b"", [Field2(0), Field2(0)], []), (b"", [Field2(1), Field2(1)], []), (b"", [Field2(1), Field2(0)], []), (b"", [Field2(0), Field2(1)], [])]))
b'09c6'
```

|Level|Control bit index|Value|Encoded byte offset|Encoded bit position (LSB=0)|
|---|---|---|---|---|
|0|0|0|1|0|
|0|1|1|1|1|
|1|0|1|1|2|
|1|1|0|1|3|
|2|0|0|1|4|
|2|1|0|1|5|
|3|0|1|1|6|
|3|1|1|1|7|
|4|0|1|0|0|
|4|1|0|0|1|
|5|0|0|0|2|
|5|1|1|0|3|

**Comment by cjpatton** [comment]
I'd be happy with this change, though I'm less certain about moving away from the representation of IPDF indices as integers.

**Comment by schoppmp** [comment]
I think we should use integers only if the particular integer type supports all methods we need (e.g., accessing individual bits), and if we need their semantics (e.g., we use them as indices, for counting, or similar). That might be the case for the IDPF index, which can correspond to an array index into the (fully evaluated) output domain. For control bits I'm less certain, and in my [C++ implementation](https://github.com/google/distributed_point_functions/blob/master/dpf/distributed_point_function.proto#L114) I actually just saved them as individual booleans.

**Comment by divergentdave** [comment]
Above, I said that the Poplar1 measurement and aggregation parameter use the same bit ordering as the packed control bits. This is incorrect, measurements have the first bits in the most significant part of the integer, while packed control bits have the first bits in the least significant part of the integer.

In `IdpfPoplar.gen()`, bits are extracted with `keep = (alpha >> (IdpfPoplar.BITS - level - 1)) & 1`. Similarly, in `IdpfPoplar.eval()`, bits are extracted with `bit = (prefix >> (level - current_level)) & 1`.

In `IdpfPoplar.encode_public_share()`, bits are combined with `packed_ctrl |= ctrl_cw[0].as_unsigned() << (2*level)`, etc. In `IdpfPoplar.decode_public_share()`, bits are extracted with `packed_ctrl & 1` and `(packed_ctrl >> 1) & ` followed by `packed_ctrl >>= 2`.

**Comment by divergentdave** [comment]
I opened #151 to flip the IdpfPoplar public share's control bits around. I think there's no need to make any changes to the measurement or aggregation parameter based on the discussion here.
