### ISSUE TITLE
Poplar1: Hoist decision from prep_next to prep_shares_to_prep

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#169]
Currently, the final sketch validity check is done in `prep_next()` on round 2. This check only depends on the prepare message, so we could hoist it into `prep_shares_to_prep()`, as we previously did for Prio3. If we made this change, and dropped the optimization that substitutes the empty string instead of zero vectors, this would simplify implementations by making prepare message lengths predictable from knowledge of any aggregator's prepare state.

**Comment by cjpatton** [comment]
Sounds like a good change to me, but we do need to match the spec here I think. What does the spec say?

**Comment by cjpatton** [comment]
Oops, I thought you posted this to divviup/libprio-rs. SGTM.
