### ISSUE TITLE
What to do about DAFs (VDAFs w/o verifiability)

### ISSUE THREAD

**Issue by cjpatton** [cfrg/draft-irtf-cfrg-vdaf#20]
The syntax is compatible with schemes that forego verifiability altogether, but calling such a scheme a "VDAF" would be misleading. It's probably a good idea to make this distinction explicit, i.e., define "DAFs" as 0-round VDAFs that provide no verifiability. Should we make room for this in this document, or does it make sense to kick this to a different document?

Note that this question came up previously in the context of PPM: https://github.com/abetterinternet/ppm-specification/issues/45.

**Comment by chris-wood** [comment]
In case it helps, the [VOPRF document](https://cfrg.github.io/draft-irtf-cfrg-voprf/draft-irtf-cfrg-voprf.html) includes OPRFs with and without verifiability. I think it makes sense to include DAFs in this document, especially for deployments that don't need verifiability.

**Comment by cjpatton** [comment]
One example of something that's close to a DAF: https://eprint.iacr.org/2018/442.pdf

**Comment by cjpatton** [comment]
One thing @chris-wood and I noted today is that "DAFs" will have no need for a verification parameter, making them syntactically somewhat different.
