### ISSUE TITLE
Review 05: Chris Wood: Ideas for intro

### ISSUE THREAD

**Issue by cjpatton** [cfrg/draft-irtf-cfrg-vdaf#219]
>The overview of Prio3 and Poplar1 in the introduction feels a bit too out of place, especially as it comes before the generic overview. I would suggest removing this content, as it's somewhat redundant with the section in {{prio3}} and {{poplar1}}.
>
> Moreover, to align with the structure of the document, I might try to reframe the intro to first introduce DAFs, and then introduce malicious clients and the need for verifiability, and then introduce VDAFs. I can propose some text for this if you'd be interested.

**Comment by bkmgit** [comment]
A introduction with more generic examples would be great.  Some requirements on non-colluding servers would also be helpful, in particular how many servers have been used/should be used in practice and whether there is a time period where collusion can be problematic.

**Comment by cjpatton** [comment]
@chris-wood would you like to take a swing at this, since you offered?

**Comment by cjpatton** [comment]
> @bkmgit: Some requirements on non-colluding servers would also be helpful, in particular how many servers have been used/should be used in practice and whether there is a time period where collusion can be problematic.

There's a PR up to address this. I ended up sticking the discussion about non-collusion and the number of aggregators into security considerations, where I feel this discussion is more appropriate.
