### ISSUE TITLE
Remove aliases of primitive Python types

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#222]
We would like to remove aliases of primitive types in `common.py`, and just use the primitive types straight out of their global bindings.

_Originally posted by @cjpatton in https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/221#discussion_r1167331240_

**Comment by cjpatton** [comment]
We should just change `Vec` to `list`, right?
