### ISSUE TITLE
Making Prio3Histogram's measurements more flexible

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#239]
Currently, Prio3Histogram is parameterized by a list of bucket boundaries, and its measurement is a `Integer` that gets compared to all these boundaries, to determine which bucket's counter should be incremented. The same validity circuit has broader application than 1D histograms of integers that are directly supported. For instance, histograms with floating point numbers, multi-dimensional histograms, and multiple choice survey questions could all benefit from the same one-hot/mutual exclusion validity circuit, but using them with the VDAF as defined today would require defining awkward mappings. (i.e. creating a synthetic list of bucket boundaries, and providing measurements chosen to land in particular buckets) Similarly, someone may want a histogram with bucket intervals that are closed on the left instead of on the right.

I think we should either define a separate Prio3 VDAF, or redefine the Prio3Histogram VDAF, so that it takes a number of buckets as a parameter, and either a bucket index or a vector with a single 1 as a measurement. This would require most use cases to do some preprocessing before calling the shard function, but it wouldn't require turning floating point or vector inputs into an integer to be compared against synthetic bucket boundaries. Plus, replacing the array in the `buckets` parameter with a single cardinal number would make passing around VDAF parameters out of band easier. In ENPA, we handled metrics with over a thousand buckets, as a point of reference. (note that the aggregators have only ever cared about the number of buckets, and not the boundary values) Since this only affects the measurement and parameters, we could maintain wire and proof compatibility. I could prototype out the new interface in libprio-rs, maybe under a name like 'raw histogram'.

**Comment by cjpatton** [comment]
SGTM. Since no one is using Prio3Histogram yet, I'd say it would be alright to replace it. I'd personally be comfortable with the same name, but if a distinguished name would be useful, then Prio3RawHistogram sounds like a fine name to me. (In this case I think we'd also want to change the codepoint.)

**Comment by tgeoghegan** [comment]
I'm with Chris, in that I hope it's still early enough in VDAF and DAP's lifespan that we can just change how `Prio3Histogram` works instead of forever carrying around two histogram types, one of which should probably never be used.
