### ISSUE TITLE
Consider merging `VDAF.prep_init` with the initial `VDAF.prep_next`.

### ISSUE THREAD

**Issue by branlwyd** [cfrg/draft-irtf-cfrg-vdaf#244]
Currently, the VDAF preparation process will always follow the initial call to `VDAF.prep_init` with a call to `VDAF.prep_next`. We should consider merging these calls such that the "new" `VDAF.prep_init_new` is a sequence of `VDAF.prep_init_old` followed by `VDAF.prep_next`. There are a few upsides to this API layout:

The API & preparation sequence would be simplified: for example, `prep_next`'s `inbound` parameter would no longer need to be optional. Error handling to users of this API would also be simplified, though in the spec a blanket exception catch is used so this point is moot.

This API layout also matches how `libprio-rs` implements the VDAF API, and will likely soon be how `divviup-ts` implements the VDAF API, so there is evidence that this API layout is preferable to some implementations. Matching the specification to the "natural" implementation will likely ease human understanding of the spec & its implementations.

**Comment by cjpatton** [comment]
This was discussed before (https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/77). We decided then to leave open the possibility of a 0-round VDAF, but this is looking to be unlikely. I would be in favor of assuming VDAFs have at least 1 round and making this change. What do you think, @schoppmp?

**Comment by wangshan** [comment]
I think this is a good idea. but it also requires some re-write of the ping-pong topology, which has a ping_ping_start that calls the old prep_init only, followed by a ping_pong_req/resp which will call prep_next.

**Comment by schoppmp** [comment]
I agree that this is a good idea that would simplify things, and I don't think keeping the option for 0-round VDAFs is worth it anymore.
