### ISSUE TITLE
Add extra test vectors with more than two shares

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#245]
We should add additional test vector files for each VDAF that split into more than two shares, for better coverage.

**Comment by cjpatton** [comment]
Sounds reasonable, but how many shares? Would we 2 and 3, say, or just 3?

Also, did you detect a bug that these test vectors would have covered?

**Comment by divergentdave** [comment]
A combination of 2 and 3 shares sounds good. This came up during implementation in divviup-ts, with a latent bug in slicing seeds that happened to not be an issue with two shares.
