### ISSUE TITLE
Consider providing "rand" directly in test vectors

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#246]
Currently, producing test vectors requires taking RAND_SIZE many bytes from the sequence [0, 1, 2, 3, ..., 254, 255, 0, 1, 2, ...]. We could instead provide the "rand" input in test vector files directly, hex encoded, so other implementations don't have to re-implement this detail of the test vector generation.

**Comment by cjpatton** [comment]
That seems fine to me. It. would be a little redundant to stick in the Appendix, but would definitely be helpful in the machine-readable test vectors.
