### ISSUE TITLE
Consider replacing ping_pong_* with input_share_to_out_share_*

### ISSUE THREAD

**Issue by wangshan** [cfrg/draft-irtf-cfrg-vdaf#252]
The functions begin with `ping_pong` is specific to the topology, the rest of VDAF interface specifies the purpose of each step, which I think makes more sense.

To make it consistent with `VDAF.measure_to_input_shares`, `VDAF.out_shares_to_agg_share`, `VDAF.agg_shares_to_result`, I think we should replace `ping_pong` with `input_share_to_out_share`. For e.g.
```
input_share_to_out_share_start
input_share_to_out_share_req
input_share_to_out_share_resp
```

Related, I have a few other thoughts about the ping pong steps.
* Intuitively, I would think ping_pong_start transition the state to Start, but it actually transits to either Continue or Rejected.
* Do we want to separate `ping_pong_req` and `ping_pong_resp`? they are essentially the same state transition step on Continue state, just react differently on input.

**Comment by cjpatton** [comment]
@wangshan can you take another look at this issue and let us know if there's anything else to do here?
