### ISSUE TITLE
Message exchange described in ping pong topology does not match those in DAP arg-init

### ISSUE THREAD

**Issue by wangshan** [cfrg/draft-irtf-cfrg-vdaf#254]
DAP's egg-init section https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/blob/main/draft-ietf-ppm-dap.md#aggregate-initialization-agg-init described the message exchange as following:

leader calls `VDAF.ping_pong_start`
leader calls `VDAF.ping_pong_req`, which returns state and `outbound` Message.
leader constructs a `PrepareInit` message with the `outbound` Message.

helper calls `VDAF.ping_pong_start`
helper calls `VDAF.ping_pong_resp`, which returns state and `outbound` Message.
helper constructs a `PrepareResp` message with the `outbound` Message:

> This procedure determines the initial per-report state, as well as the initial outbound to send in response to the Leader. If state == Rejected(), then the Helper responds with
> 
> struct {
>   ReportID report_id;
>   PrepareRespState prepare_resp_state = reject;
>   PrepareError prepare_error = vdaf_prep_error;
> } PrepareResp;
> Otherwise the Helper responds with
> 
> struct {
>   ReportID report_id;
>   PrepareRespState prepare_resp_state = continue;
>   opaque payload<0..2^32-1> = outbound;
> } PrepareResp;

But this doesn't match what's in `ping_pong_transition`, which I believe will send out a `Finish` message. Besides, there is no Reject Message type, while DAP's `PrepareRespState` doesn't have an `Initialise` message type.

I think the underlying logic for the simplified ping-pong topology is relatively clear, perhaps we can replace VDAF.Message and DAP.PrepareRespState with a `VDAF.PrepareState` type that just reflects the current _host_ state machine, and let peer react based on host state, peer state and peer state associated data:

- leader prepares locally, with leader_input_share
  - if failed, transit to `Reject` state, terminal
  - otherwise transit to `Continue` state, sends a _Continue_ message to helper, with state associated data: leader_prep_share
- helper prepares locally, with helper_input_share
  - if failed, transit to `Reject` state, helper responds with _Reject_ message
  - otherwise transit to `Continue` state
- helper completes the preparation
  - if failed, transit to `Reject` state, helper responds with _Reject_ message
  - otherwise transit to `Finish` state, helper responds with _Finish_ message, and state associated data: prep_msg
- leader completes the preparation, 
  - if received _Reject_ message, transit to `Reject` state, terminal
  - if final prep failed, transit to `Reject` state, terminal
  - otherwise transit to `Finish` state, terminal

**Comment by cjpatton** [comment]
> But this doesn't match what's in `ping_pong_transition`, which I believe will send out a `Finish` message. Besides, there is no Reject Message type, while DAP's `PrepareRespState` doesn't have an `Initialise` message type.

The way to think of`ping_pong_resp()` is that `outbound` is only set (i.e., not equal to `None`) if there is a message to send:
* If the Helper reaches the `Rejected` state, then there is no message to send.
* Else If the Helper reaches `Continued`, then there is a message to send.
* Else if the Helper reaches `Finished`, then there is a message to send.

**Comment by cjpatton** [comment]
I don't think it's necessary that we do this at the VDAF level. Please take a look at the latest DAP draft: I claim that there it is unambiguous how to process each of the reports in the aggregation flow. If there is an issue let us know!

**Comment by wangshan** [comment]
if the message exchange in ping_pong is for illustration only, then I agree DAP's description is the single source of truth.

**Comment by cjpatton** [comment]
To be clear: VDAF *does* prescribe the format of the byte string passed to and from the ping pong API. DAP then takes these strings and does something with them, opaquely, without trying to parse them.

**Comment by wangshan** [comment]
close this since the new ping pong api clarifies the state transitions.
