### ISSUE TITLE
A diagram to show the relationship of different terms in FLP

### ISSUE THREAD

**Issue by wangshan** [cfrg/draft-irtf-cfrg-vdaf#257]
There are many terms discussed in the generic FLP section (https://github.com/cfrg/draft-irtf-cfrg-vdaf/blob/main/draft-irtf-cfrg-vdaf.md#a-general-purpose-flp-flp-generic):
Gadgets, Validity Circuits, Proof, Prover, Verifier, etc. A diagram shows the relationship between them would make the text easier to follow.

**Comment by cjpatton** [comment]
We can definitely whip up a ladder diagram for this.
