### ISSUE TITLE
Make DAF a special case of VDAF and move it to sections after VDAF

### ISSUE THREAD

**Issue by wangshan** [cfrg/draft-irtf-cfrg-vdaf#259]
This had been discussed in: https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/20. I think it was right to name DAF explicitly and keep it in this document. However, since DAF is at the beginning of this doc, a lot of the key components of VDAF is introduced from DAF, the reader would have to refer to DAF section for the common part and figure out what's the difference. Given that DAF is not recommended and not the main focus of this document, shall we move it to somewhere after VDAF. So section 4 can be definition of VDAFs, right after Overview. 

DAF can be explained as a VDAF without a verification system, maybe it makes sense to mention it after Poplar1? We can try to keep the same interface between DAF and VDAF, but specify parameters like `nonce` and `verify_key` are not used (I imagine this would be how it will be implemented), or still keep the separate interface.

**Comment by cjpatton** [comment]
Nonce has been added to the API, so this is ready to close. We'll consider removing DAFs altogether in #346.
