### ISSUE TITLE
Use verb to describe the 4 stages of VDAF

### ISSUE THREAD

**Issue by wangshan** [cfrg/draft-irtf-cfrg-vdaf#260]
Change all functions to prepend a verb, for eg. `measurement_to_input_shares` -> `shard_measurement_to_input_shares`, `out_shares_to_agg_share` -> `aggregate_out_shares_to_agg_share`, this not only matches the description of the text (4 stages) but also follows common coding styles. 

We can go future by only keeping the verb, as long as we define all the associated types. `shard(Measurement, ...) -> tuple[PublicShare, Vec[InputShare]]` is as more clear and concise than `shard_measurement_to_input_shares(Measurement, ...) -> tuple[Bytes, Vec[Bytes]]`. This is basically what libprio.rs is doing anyway.

**Comment by cjpatton** [comment]
I have no objection. The names "shard", "prepare", "aggregate", and "unshard" are fairly well-established. @bifurcation came up with the original naming scheme, so we'll make sure to get his review on the PR.
