### ISSUE TITLE
Clarify threat model for robustness

### ISSUE THREAD

**Issue by jimouris** [cfrg/draft-irtf-cfrg-vdaf#304]
Hello, I had a discussion with @cjpatton and @pratiksarkar93 about the VDAF security considerations. The draft states:

```
 VDAFs have two essential security goals:

 1.  Privacy: An attacker that controls the network, the Collector,
     and a subset of Clients and Aggregators learns nothing about the
     measurements of honest Clients beyond what it can deduce from the
     aggregate result.

 2.  Robustness: An attacker that controls the network and a subset of
     Clients cannot cause the Collector to compute anything other than
     the aggregate of the measurements of honest Clients.
```

I was wondering if the notion of **robustness** is referring only to **correctness** or to both correctness and **guaranteed output delivery (GOD)**. Would it make sense to split robustness into these two properties to use more formal MPC terms (i.e., [pages 2 & 3 from Lindell's paper](https://eprint.iacr.org/2020/300.pdf))? 

For example, the draft states "break robustness" or "attack on robustness" but it is not clear if that means to cause the Collector to output an incorrect result (i.e., attack on correctness) or to prevent honest parties from receiving their output (i.e., attack on GOD).

**Comment by divergentdave** [comment]
Yes, a dishonest Aggregator can cause the Collector to output an incorrect result by sending an arbitrary aggregate share, or prevent the protocol from completing by not sending proscribed messages during the aggregation flow or collection flow. I think we should spell out both kinds of outcomes, and we could connect them to these MPC terms, but I think we should still use "robustness" throughout the bulk of the document. Thus far, no proposed VDAF would lack guaranteed output delivery but have correctness in the face of one dishonest Aggregator, so we don't need to make a distinction once all the terms are introduced. Additionally, "robustness" is used in the referenced papers, including the original Prio paper (from NSDI in 2017) and the 2023 Davis et. al. paper.

**Comment by jimouris** [comment]
That makes sense, thank you both for clarifying! Personally, I think "correctness" is well-defined in MPC whereas "robustness" might be a bit ambiguous. In the Prio paper, it's clear that it refers to correctness, but I've seen it used freely.

I think either term is fine, as long as there is a clarification somewhere that robustness refers to the notion of correctness.

**Comment by pratiksarkar93** [comment]
Usually in MPC **correctness** refers to the setting where everyone is honest and the protocol output is the same as the function (being computed) output. 
In MPC terminology, Robustness considers the setting where one of the aggregators behaves maliciously. This inherently also implies that a malicious aggregator cannot affect the protocol output. If it does change the output then the honest parties will detect it. 

I think a better way to rephrase robustness is by breaking it up into two properties, following the terminology used in Section 2.3 of **Poplar** :
1. Robustness/guaranteed output delivery against malicious clients. 
2. Privacy of honest clients against a malicious aggregator/collector 

And correctness should be separate. 

Let me know what you think.

**Comment by cjpatton** [comment]
Hi @pratiksarkar93, I believe the way we've split it up in the draft already matches your suggestion.

**Comment by cjpatton** [comment]
On the other I hand I might be misunderstanding you. Perhaps you'd consider writing a PR that aligns the Security Considerations section with the correct terminology?

**Comment by pratiksarkar93** [comment]
@cjpatton  Yes the draft is aligned with what I was proposing. The terms "robustness" and "privacy" need to be elaborated more. I can do that in the Security Considerations section.

**Comment by cjpatton** [comment]
Summarizing TODOs from this issue and offline discussions:

- [ ] Clarify that an attacker that controls the network can break guaranteed-output-delivery
- [ ] Clarify distinction between robustness against malicious Clients and robustness against malicious Clients and Aggregators (the draft's goal is the former).
