### ISSUE TITLE
Consider generalizing `num_shares` in `Flp` interface

### ISSUE THREAD

**Issue by junyechen1996** [cfrg/draft-irtf-cfrg-vdaf#314]
Under [Flp](https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-08.html#name-fully-linear-proof-flp-syst) interface, the APIs contain a parameter `num_shares` which seems to be something useful in certain FLP constructions, e.g., FLPs that need to normalize a constant if it's not multiplied with a secret-shared variable. I wonder if this parameter can be more generic to tailor the need for each FLP. Some use cases that may benefit from this:

- Avoid re-computation of variables that stay the same in each FLP proof in [multiproof setting](https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-08.html#name-multiple-proofs). In #177  and #305 , the VDAF spec added support to allow a VDAF to run multiple proofs of its FLP to improve robustness. Inside the `eval()` function used by both `prove()` and `query()`, the FLP may compute "some variables" locally, which will then be fed as inputs to gadgets. Those variables don't change within each proof, so the VDAF may choose to compute those variables once, and feed them to each FLP's proof repetition to save computation time. Examples include the `sum_check` variable in [`Prio3Histogram`](https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-08.html#name-prio3histogram), which only needs to be computed once, and stays the same for all FLP proof repetitions.

- FLPs that prefer to sample random values from a seed directly, instead of passing the random values as field elements in `joint_rand` to `prove()` and `query()`. The benefit include: (1) if the FLP uses a large number of field elements, it may prefer to sample the field elements on the fly instead of keeping all field elements in memory. (2) If the FLP prefers to not use field elements to represent its random values, (e.g., it may only want to sample binary values), so it's more convenient for FLP to sample from a random buffer directly, e.g., by looking at the random buffer bit by bit.

Perhaps we can generalize today's `num_shares` parameter to a FLP-specific struct to support these use cases? Note this won't be wire breaking to the VDAF interface, but improves the flexibility of the integration between VDAF and FLP.

**Comment by cjpatton** [comment]
This sounds like a useful improvement to me. I'm imagining something like an associated type for the `Valid` API. Call it something like `Context`, or `EvaluationParam`?

**Comment by junyechen1996** [comment]
I realized there is not enough motivation to complicate the spec with this change right now, so closing it.
