### ISSUE TITLE
PRG: Fixed-key AES

### ISSUE THREAD

**Issue by cjpatton** [cfrg/draft-irtf-cfrg-vdaf#32]
Our initial PRG construction is based on AES: https://github.com/cjpatton/vdaf/pull/28. @schoppmp points out that there may alternative AES-based constructions that are better suited to our application. In addition, there may be alternative primitives, like an XOF hash function, that are well suited for VDAFs. This issue is for tracking this discussion.

**Comment by cjpatton** [comment]
Here's the paper Phillipp referenced: https://eprint.iacr.org/2019/074.pdf

**Comment by martinthomson** [comment]
The text you added to the draft suggests that fixed-key AES (as it is called in the paper) might be something to move to.  The paper suggests that you don't get correlation robustness in that case, so maybe that isn't the best choice.

A PRG based on AES does seem to be a sensible choice here from a performance perspective if nothing else, and the idea of using a counter seems reasonable.  Maybe consider using $\mathsf{MMO}^\pi$ or $\widehat{\mathsf{MMO}}_\sigma^\pi$ from that paper instead.  The added cost is modest, but it would appear that the properties they provide are superior.

**Comment by martinthomson** [comment]
Oh, I should add https://eprint.iacr.org/2022/080 describes another variant that adds a tweak.  The tweak looks like $H(m,t) = \pi(m\otimes t)\xor (m\otimes t)$, which is a little slower overall, but probably still in line with what you are looking for.  The only trick there is in deciding the tweak.

**Comment by wangxiao1254** [comment]
I was contacted by Phillipp @schoppmp about this issue and we had some discussion. Briefly, letting each client pick a uniform AES key seems the best option. The underlying reasoning would be based on https://eprint.iacr.org/2019/1168.pdf, MiTCCR, in the ideal cipher model. The loss of concrete security would be minimal.

**Comment by cjpatton** [comment]
Thanks @wangxiao1254 for your feedback and contribution to the design of VDAF!
