### ISSUE TITLE
Is it OK to mention specific companies/projects?

### ISSUE THREAD

**Issue by cjpatton** [cfrg/draft-irtf-cfrg-vdaf#338]
The intro mentions the MOzilla Origin Telemtry project, ENPA, ISRG, Google, and Apple by name. I'm not sure this is appropriate for an RFC to do.

**Comment by richsalz** [comment]
Credit them in the acknowledgements for providing the impetus to write the draft?

**Comment by cjpatton** [comment]
Great idea, thanks Rich!

**Comment by cjpatton** [comment]
List feedback: https://mailarchive.ietf.org/arch/msg/cfrg/4TAP3_bgDGFEy8C29qigQUwNc2A/
