### ISSUE TITLE
Prio3: Store compressed helper input share in PrepState

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#380]
Currently, the PrepState for Prio3 is `tuple[list[F], Optional[bytes]]`, consisting of the output share and the recomputed joint randomness seed. We could improve the storage requirements for the helper if the helper instead stored its compressed input share seed, and then re-expanded and re-truncated it into an output share during prep_next(). I think the leader should still store its output share in the PrepState, as it may be shorter than the leader input share, depending on the Prio3 instance. This would be quasi-wire breaking, in that it would change the format of an aggregator's persistent storage, but wouldn't affect messages between parties.

**Comment by cjpatton** [comment]
Does this need to be specified, or would an implementation note suffice? libprio already does this, fwiw:
https://github.com/divviup/libprio-rs/blob/main/src/vdaf/prio3.rs#L1045

I don't think this is a wire breaking change because the prep state is never transmitted between parties.

**Comment by divergentdave** [comment]
Ah good point. An implementation note would be good, in that case.
