### ISSUE TITLE
Does VDAF need a notion of leader?

### ISSUE THREAD

**Issue by tgeoghegan** [cfrg/draft-irtf-cfrg-vdaf#40]
PPM has a notion of a distinguished aggregator called the "leader". Wherever messages contain a sequence of objects, that protocol insists that the leader's share always be the first element (e.g. [`Report.encrypted_input_shares`](https://www.ietf.org/archive/id/draft-gpew-priv-ppm-01.html#section-4.2.2-4.4)).

VDAF only references the notion of a leader in its specification of `Prio3`, [whose input sharding algorithm does specify that the leader's share appears first](https://www.ietf.org/archive/id/draft-patton-cfrg-vdaf-01.html#section-6.2.2).

However that constraint isn't articulated generically for all VDAFs, which leaves things ambiguous for implementations. Consider the current generic declaration of [`prio::vdaf::Client::shard`](https://docs.rs/prio/latest/prio/vdaf/trait.Client.html):
```
    /// Shards a measurement into a sequence of input shares, one for each Aggregator.
    fn shard(
        &self,
        public_param: &Self::PublicParam,
        measurement: &Self::Measurement,
    ) -> Result<Vec<Self::InputShare>, VdafError>;
```
PPM implementations have to guess that the 0th element in the returned `Vec` is the leader's share. Should the [VDAF-level definition of `shard`](https://www.ietf.org/archive/id/draft-patton-cfrg-vdaf-01.html#section-4.2) discuss the notion of a leader share, and require that the 0-th value returned from `Vdaf.measurement_to_input_shares` be the leader's?

**Comment by cjpatton** [comment]
I agree this ambiguity matters to PPM -- or, more generally, the Leader/Model architecture -- insofar that it makes sense to send the "big" share to the leader in order to decrease communication cost for the helpers. It's also true that this asymmetry --- i.e., the existence of a distinguished "big" share -- exists for Prio3 and, to a lesser extend, Poplar1; but it's worth pointing out that the asymmetry doesn't necessarily exist for all VDAFs.

For this reason, my view here is that it's not worth making a syntactic change to the VDAF spec in order to accommodate this. What I would go for is adding guidance somewhere in the spec to nudge things in the right direction. In particular: would be sufficient to RECOMMEND that future VDAFs put the "big" share first (if it exists)?

**Comment by tgeoghegan** [comment]
I'm not sure that a recommendation will suffice. If there's a difference in the encoding of one share vs. the others, then a PPM implementation needs to able to tell which one is different so it can be sent to the aggregator that is configured to handle that kind of share.

Alternatively, an encoded input share could include some indication of how it is encoded (e.g. whether or not it's compressed in prio3) and then `Vdaf.prep_init` could use that inline information to decide how to decode the input share.

**Comment by cjpatton** [comment]
> I'm not sure that a recommendation will suffice. If there's a difference in the encoding of one share vs. the others, then a PPM implementation needs to able to tell which one is different so it can be sent to the aggregator that is configured to handle that kind of share.

True enough. Right now the information needed to decode (and indeed to prepare an input) is encoded by the verification parameter: https://www.ietf.org/archive/id/draft-patton-cfrg-vdaf-01.html#name-setup-2. This seems sufficient, but  perhaps there's a better way to expose this?

By the way, to decode a Prio3 input share, you need to know whether the share is for the "leader" or a "helper". You also need the the verification parameter encodes an "aggregator ID", which is used in an essential way to compute the joint randomness. For Prio3 this is encoded by the verification parameter.

> Alternatively, an encoded input share could include some indication of how it is encoded (e.g. whether or not it's compressed in prio3) and then `Vdaf.prep_init` could use that inline information to decide how to decode the input share.

Seems reasonable, though it would cost a few bits of communication.

**Comment by BranLwyd** [comment]
I don't think VDAFs need the notion of a leader -- but I do think that the VDAF spec should consider specifying that for the various per-aggregator parameters, values are correlated by index (so e.g. `verify_params` index 0 is always used with `input_shares` index 0). The only text I can find suggesting this is in the `run_vdaf` pseudocode in Section 4.6, but I am not sure this is normative.

Separately, PPM should specify that the leader uses VDAF index 0, helper uses index 1 (or vice versa).

**Comment by cjpatton** [comment]
Right, there is currently no normative text regarding which server gets which share. I also don't think there should be, at least not in the VDAF spec. On the other hand, I agree we need language here to make sure that
(1) it's possible for PPM to specify which server gets which share.
(2) Users are guided towards making sensible choices which servers consume the "big" shares (when applicable).

I welcome suggestions for ways to solve each of these :)

**Comment by cjpatton** [comment]
@tgeoghegan, @branlwyd: Where are you two on this issue? Are you OK with me closing without a fix, or is there more you'd like to do here?

**Comment by branlwyd** [comment]
I'm OK with closing this issue -- I don't think there's anything to be done against the VDAF spec. (FWIW, I think the DAP spec defines things appropriately at this point, as well.)

**Comment by tgeoghegan** [comment]
Yeah, it seems like Daphne and Janus both figured it out. I suppose there's nothing to be done here until we hear that implementors find this confusing enough that it's worth clarifying.
