### ISSUE TITLE
IDPF: Change APIs to take alpha as a bit string, not an integer

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#416]
As discussed in the 2024-09-06 call, we should change the IDPF gen() and eval() methods to take in bit strings (lists of booleans) instead of bigints. Iterating over the bits of the bit string would be clearer than shifting and masking an integer. We'll likewise need to change the recommendation for handling byte string, which currently suggests `from_be_bytes()`, and rewrite the prefix packing done in the aggregation parameter encoding/decoding.

**Comment by cjpatton** [comment]
I labeled this as wire breaking, as this may be a possibility.

**Comment by cjpatton** [comment]
> I looked at various options for IDPF index interpretation, encoding order, and alignment. I focused on the options that satisfy the property that the encoding of a single IDPF index and the encoding of a prefix of that index share the same initial bytes. (this will solve the first ergonomics issue)

+1 Let's make sure we have this property.

> Once this is decided, the next question is whether the partial byte (now at the end of the encoding) should be "filled in" from the MSB side or the LSB side. Both are easy to implement in libprio-rs, as we would use `BitVec<u8, Msb0>` or `BitVec<u8, Lsb0>` from the `bitvec` crate as-is. Currently, we regard the MSB of a byte as the "first" bit, so I figure we may as well stick with that convention.

What do you mean by "first" bit? I think of `byte & 1` as the least signficant bit and `byte >> 7` as the most significant bit.
 
> Lastly, we have a choice to either tightly pack all prefixes together, or to pad out each prefix with zeros to the next byte boundary. We currently do the former, and this is the bandwidth-optimal choice. We could switch to padding, which would make implementations a bit easier, since this requires less shifting, and would make hex dumps of aggregation parameters more easily legible. I haven't decided whether I want to pursue this change or not, so I'm going to punt and not include it in my first PR.

I'd go for ease of implementation here. In my opinion, the complexity of the current implementation is outweighs the bandwidth savings (one byte pre prefix).

**Comment by divergentdave** [comment]
> What do you mean by "first" bit? I think of `byte & 1` as the least signficant bit and `byte >> 7` as the most significant bit.

Right, I agree on the definition of MSB and LSB. The question at hand is, when we start with an IDPF index representing a string of bytes, in what order we assign the bits from each byte to IDPF tree levels? We can start with the MSB or LSB, and produce a consistent system either way, but for each possible order, there's a different natural choice for encoding prefixes to byte strings. I've been working through the toy example of "Cat"/"\x43\x61\x74" as an input, and taking the 10-bit prefix. If we start from the MSB first, then the prefix is "\x43\x40", with the lower 6 bits of the second byte unused, otherwise if we start from the LSB first, then the prefix is "\x43\x01", with the upper 6 bits of the second byte unused.

**Comment by cjpatton** [comment]
No preference for me :)

**Comment by divergentdave** [comment]
Another reason to treat the MSB of a byte as the first bit: this results in lexicographic ordering of bit strings matching lexicographic ordering of the original byte strings. Since we have a requirement in Poplar1 that candidate prefixes be provided in order, this can make sorting and checking that order simpler and cheaper.
