### ISSUE TITLE
Representing 'linear state machine' requirement in pseudocode

### ISSUE THREAD

**Issue by divergentdave** [cfrg/draft-irtf-cfrg-vdaf#42]
The following currently appears in section 4.3.

> TODO Consider how to bake this "linear state machine" condition into the syntax. Given that Python 3 is used as our pseudocode, it's easier to specify the preparation state using a class.

**Comment by divergentdave** [comment]
My suggestion: If we augment our pseudocode with dependent types, then we could parameterize the type of `Prep` by how many rounds are left before the output share is recovered. Making up some syntax, this would look like:

```
Vdaf.prep_init(verify_param: VerifyParam, agg_param: AggParam, nonce: Bytes, input_share: Bytes) -> Prep[ROUNDS]

Vdaf.prep_next(prep: Prep[ROUNDS], inbound: Bytes) -> If[ROUNDS == 0, OutShare, Tuple[Prep[ROUNDS - 1], Bytes]]
Vdaf.prep_next(prep: Prep[R such that R < ROUNDS], inbound: None) -> If[R - 1 == 0, OutShare, Tuple[Prep[R - 1], Bytes]]
```

**Comment by cjpatton** [comment]
That's an interesting idea. It would be great to see a PR with this idea implemented. Two constraints I'd like to keep top of mind:
(1) If possible, our "pseudocode" ishould syntactically correct Python3 (well, Sage really.)
(2) Readability is more important than rigorous type semantics.

**Comment by divergentdave** [comment]
Sure, I'll noodle on that. I'm not sure Python typing can express the concept directly, but maybe we could show ~3 `@overload`s with `Literal[1]`, `Literal[2]`, `Literal[3]`, as parameters, etc.
