### ISSUE TITLE
Should each code listing have a caption?

### ISSUE THREAD

**Issue by cjpatton** [cfrg/draft-irtf-cfrg-vdaf#453]
When we specify an algorithm, sometimes we give it a figure number and caption, sometimes we don't. Which do we prefer? We don't (nor can we?) refer to these figures in the doc; we instead refer to the section that contains them.

At last count on my current development branch, we have 32 figures in the draft. If we reduced the figures to only drawings, then it would be easier to refer to them simply becausae there are less of them.

**Comment by divergentdave** [comment]
FWIW figures can be referred to, but they need an anchor name to be declared first. See `dap-topology` in DAP, for example.
