### ISSUE TITLE
Define a method for merging multiple aggregate shares into an aggregate share

### ISSUE THREAD

**Issue by tgeoghegan** [cfrg/draft-irtf-cfrg-vdaf#47]
A VDAF must define a few [associated types](https://github.com/cjpatton/vdaf/blob/15c6abadc46d760a2b39a5708492a195fb4ee2e9/draft-patton-cfrg-vdaf.md?plain=1#L400):

```
| `OutShare`    | Type of each output share     |
| `AggShare`    | Type of each aggregate share  |
| `AggResult`   | Type of the aggregate result  |
```

VDAF defines a method for combining multiple output shares into an aggregate share: [`Vdaf.out_shares_to_agg_share(agg_param: AggParam, output_shares: Vec[OutShare]) -> agg_share: AggShare`](https://github.com/cjpatton/vdaf/blob/15c6abadc46d760a2b39a5708492a195fb4ee2e9/draft-patton-cfrg-vdaf.md?plain=1#L590). That's implemented in libprio as [`prio::vdaf::Aggregator::aggregate`](https://github.com/divviup/libprio-rs/blob/1bd54185d01110ff4486b8d71ed8f17f1ea77b78/src/vdaf.rs#L201).

VDAF also defines a method for combining multiple aggregate shares into an aggregate result: [`Vdaf.agg_shares_to_result(agg_param: AggParam, agg_shares: Vec[AggShare]) -> AggResult`](https://github.com/cjpatton/vdaf/blob/15c6abadc46d760a2b39a5708492a195fb4ee2e9/draft-patton-cfrg-vdaf.md?plain=1#L627). That's implemented in libprio as [`prio::vdaf::Collector::unshard`](https://github.com/divviup/libprio-rs/blob/1bd54185d01110ff4486b8d71ed8f17f1ea77b78/src/vdaf.rs#L214).

libprio's trait [`prio::vdaf::Aggregatable`](https://github.com/divviup/libprio-rs/blob/1bd54185d01110ff4486b8d71ed8f17f1ea77b78/src/vdaf.rs#L236) is meant to correspond to a VDAF `AggShare` and also provides the method `Aggregatable:merge(&self, other: &Self) -> Result<(), VdafError>`. This method is extremely useful if not required for PPM implementations which will want to implement a map-reduce strategy for constructing aggregate shares. VDAF should define a method that corresponds to libprio's `merge`, and perhaps require that the combination of VDAF output shares into aggregate shares should not depend on order of the output shares.

**Comment by tgeoghegan** [comment]
libprio also has `Aggregatable::accumulate(&mut self, output_share: &Self::OutputShare) -> Result<(), VdafError>`, for accumulating an output share into an existing `AggShare`. VDAF may also want to define that method.

**Comment by tgeoghegan** [comment]
Besides the concrete mapping of VDAF methods to the libprio interface, we came across another interesting ambiguity in #53 ([link](https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/53#discussion_r868486690)).

The current draft discusses "one-shot" vs. "streaming" aggregation. "Streaming" means that it's possible to accumulate output shares into an aggregate one at a time, and that you don't have to keep all the output shares around. Such an aggregation is enabled by the `Aggregatable::merge` method libprio defines, and makes sense for the current Prio3 and Poplar1 VDAFs. "One-shot" means that you can't combine output shares into an aggregate until you have every output share that will go into that aggregate. @divergentdave's example is a median.

I, at least, got confused about what "one shot" vs. "streaming" means and conflated it with the distinction between VDAFs that have an aggregation parameter (so you can't prepare any input shares until the collector provides `agg_param`; Poplar1 is such a VDAF)) and ones where the aggregation parameter is implicit or empty, and aggregators can prepare inputs as soon as they're uploaded (Prio3 VDAFs are like this). We should consider adding text to VDAF and/or DAP to clarify these two features of a VDAF and their implications on input preparation, assuming that I'm not the only person confused by these two things.

**Comment by cjpatton** [comment]
@tgeoghegan where are we on this? Do you think we should still define this?
