### ISSUE TITLE
Rename Prepare

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-vdaf#48]
While prepare seems to make sense in the context of the whole VDAF flow -- "prepare a thing to be aggregated" -- it's where most of the interesting VDAF work takes place. Maybe "process" or something would be better?

**Comment by cjpatton** [comment]
"process" works for me.

**Comment by tgeoghegan** [comment]
I don't think either "prepare" or "process" are particularly good (both are too generic) but "prepare" at least implies that something else is going to be done to the value (namely, being aggregated). The verb "process" carries even less information than "prepare".

If we look at Prio3 and Poplar1, what actually is happening is proof verification. Did we previously reject "verify" as the verb to use here? Is the idea that there might be some future VDAF that either doesn't verify anything or does stuff besides verification?

**Comment by cjpatton** [comment]
The reason I'm not sure "verify" is suitable is because it implies a particular MPC technique. There other possibilities, like OT-extensions + Boolean-to-Arithmetic conversion (a la Prio+) that I would like to continue to make room for.

**Comment by cjpatton** [comment]
@hannahdaviscrypto has suggested the term "refine", as in "to refine the input shares into refined shares".

**Comment by cjpatton** [comment]
When I've discussed this issue with the DAP/VDAF editors, no one is particularly enthusiastic about this change at this point. I think the ship has sailed. If anyone feels strongly about changing it (best suggestion so far is "refine"), then feel free to re-open.
