### ISSUE TITLE
Define integer division operator

### ISSUE THREAD

**Issue by martinthomson** [cfrg/draft-irtf-cfrg-vdaf#481]
I'm not a big Python user and so I didn't know what "//" did.  Outside of the code that is obviously and explicitly Python, it might help to define these things up front.  Maybe you can get away with x[i] for array indexing as that is common across many programming languages, but "//" starts a comment in many languages, so it is probably worth being crisp about what you mean.

FWIW, I would have gone with "/" personally or a more explicit `floor(a / b)`; "/" is more easily understood to mean integer results from integer operands in most languages, but I get how that isn't compatible with the choice of Python.

**Comment by cjpatton** [comment]
Great idea, we'll add `//` to conventions: https://cfrg.github.io/draft-irtf-cfrg-vdaf/draft-irtf-cfrg-vdaf.html#section-2

Also, defining array indexing is a good idea as well.
