### ISSUE TITLE
Is PROOFS ever non-unitary?

### ISSUE THREAD

**Issue by martinthomson** [cfrg/draft-irtf-cfrg-vdaf#482]
There is a lot of complexity in the draft that allows for PROOFS to be something other than 1.  But none of the instantiations ever takes that option.  Is this complexity worth keeping?

**Comment by cjpatton** [comment]
You can reduce communication cost by picking a smaller field, but this may cost you dearly in terms of robustness. Our general guidance is if you swap Field128 for Field64, then you should bump the number of proofs to three: https://cfrg.github.io/draft-irtf-cfrg-vdaf/draft-irtf-cfrg-vdaf.html#section-9.7-7

**Comment by cjpatton** [comment]
While not used in the spec today, there are non-standard Prio3 variants that are using PROOFS > 1.
