### ISSUE TITLE
Create a base class for `Daf` and `Vdaf`

### ISSUE THREAD

**Issue by cjpatton** [cfrg/draft-irtf-cfrg-vdaf#490]
Sharding, aggregation, and unsharding are meant to be identical, but we don't currently enforce this in the API.

Create a base class for sharding, aggregation, and unsharding of which`Daf` and `Vdaf` are a subclass that define different APIs for preparation.

**Comment by divergentdave** [comment]
2024/10/16 call: This would be in the reference implementation only (so the type checker can catch it if we fail to keep common methods between DAF and VDAF in sync again), and not affect the draft itself.
