### ISSUE TITLE
Should the draft be prescriptive about encoding? (was "Serialization of aggregate shares needs to be specified")

### ISSUE THREAD

**Issue by cjpatton** [cfrg/draft-irtf-cfrg-vdaf#58]
`Vdaf` implementations need to define a type`Vdaf.AggShare` for the aggregate shares. Because the aggregate share are transmitted over the network, their encoding needs to be specified. There are two solutions to consider:
(1) Replace `Vdaf.AggShare` with `Bytes`
(2) Add methods on `Vdaf.AggShare` for encoding/decoding

The other quantities written to the network are input shares, prepare message shares, and the combined prepare message for each round. If we do (2), then for consistency we should also consider defining separate encoding/decoding methods for these. Currently the methods are implicit, since the type of each of these values is `Bytes`.

**Comment by cjpatton** [comment]
My view here is that, as a general rule, the spec shouldn't expose the encoding to the user unless doing so simplifies the spec. Implementations are of course free to follow a different rule. Following this rule to the letter, we would pick (1). I'm interested to hear other takes here.

**Comment by cjpatton** [comment]
Good question. I don't think there is consensus in the CFRG: some drafts aim to be perspective about encoding, others don't. Thus far this draft has been prescriptive.

My personal view is that the specification of a cryptographic algorithm should be as prescriptive as possible. The goal of being prescriptive is to eliminate classes of bugs that occur when two different implementations of the same algorithm try to interoperate. (See https://eprint.iacr.org/2021/923 for a recent example.) Certainly the manner by which VDAF messages are encoded falls into this category. Imagine, for example, that you had a DAF (al a #53) for which one implementation chose big endian encoding of field elements and the other chose little endian.

**Comment by cjpatton** [comment]
I don't want to cut off the discussion on this thread, but I would at least like to ensure that the next draft specifies an encoding of agg shares. This is accomplished by https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/75. There are two questions raised here, which the PR explicitly punts on:
(1) Should all quantities have an explicit type, regardless of whether the type needs to be encoded?
(2) Should the document be prescriptive about encoding?

**Comment by schoppmp** [comment]
> (2) Should the document be prescriptive about encoding?

I'm okay with ensuring that our current VDAF candidates (Prio3 & Poplar1) specify encodings (so all implementations use the same endianness etc.), but I wouldn't prescribe anything at the VDAF level, and instead leave this to the specs for particular VDAFs.
