### ISSUE TITLE
Scope Questions: Public-key, Shuffling-based, and Zero-round VDAFs?

### ISSUE THREAD

**Issue by schoppmp** [cfrg/draft-irtf-cfrg-vdaf#77]
There have been a couple of issues around features in hyptothetical VDAFs that are needed by neither Prio3 nor Poplar1.
Two examples are public-key encryption based VDAFs (which are currently hard to support after the [removal of public parameters ](https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/62)), or [zero-round verification](https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/73). A third would be support for multi-round aggregation protocols that might include shuffling of individual records, to enable something like [IPA](https://docs.google.com/document/u/1/d/1KpdSKD8-Rn0bWPTu4UtK54ks0yv2j22pA5SrAD9av4s/edit).

All of these are not supported with the current VDAF syntax, and would require explicit accommodations in higher-level protocols such as [DAP](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/). The goal of this issue is to discuss and align on the question how much flexibility we want to allow in the VDAF syntax.

Some preliminary thoughts from a discussion with @cjpatton:
- In general, providing too many options to choose from in protocols leads to security issues due to increased complexity, attack surface, possibility of downgrades, and so forth. If we want to provide flexibility here, we have to ensure that we don't introduce these issues.
- We can't think of all possible syntax needs for hypothetical future constructions that semantically still fit a "verifiable distributed aggregation function". How can we extend the VDAF syntax in such cases? Do we instead want to require a new kind of object (e.g., a PK-VDAF that supports public keys), at the risk of not being compatible with higher-level protocols?

**Comment by ekr** [comment]
>    In general, providing too many options to choose from in protocols leads to security issues due to increased complexity, attack surface, possibility of downgrades, and so forth. If we want to provide flexibility here, we have to ensure that we don't introduce these issues.

I don't think this is a very strong argument in this case. This is not a situation of negotiation but rather where there is a single explicit and verified configuration, but each VDAF (or whatever) runs effectively in parallel.

> We can't think of all possible syntax needs for hypothetical future constructions that semantically still fit a "verifiable distributed aggregation function". How can we extend the VDAF syntax in such cases? Do we instead want to require a new kind of object (e.g., a PK-VDAF that supports public keys), at the risk of not being compatible with higher-level protocols?

There are two ways to extend DAP:

1. Add new VDAFs
2. Extend it to support new non-VDAF constructions

If there are new primitives that don't make sense as VDAFs but do make sense in DAP (for instance, IPA, or an ElGamal-based system like that in Adnostic), then we should do that by extending DAP.

**Comment by cjpatton** [comment]
FTR, Adnostic is https://crypto.stanford.edu/adnostic/. There is also AdScale, which is follow-on work: https://isi.jhu.edu/~mgreen/advertising.pdf

I (currently) agree with EKR, especially in light of our recent experience working VDAFs into DAP. But @schoppmp made one more point, which convinced me that we may not know yet what the best path forward is here.

In protocol design it's typical to treat symmetric-key primitives differently from their public-key analogues. For example, a protocol built around symmetric encryption is going to be different from one built around public-key encryption.

The current VDAF syntax is specialized for a specific class of schemes. In particular, it does not admit public keys. Following the design principle above, we would want to treat schemes that do (e.g., Adnostic or AdScale) as a different kind of primitive, e.g., a PK-VDAF. However, @schoppmp pointed out that, in the MPC literature, the boundaries between different classes of constructions is more blurry than "public-key" versus "symmetric".

Before making a decision here, it will be helpful to first try to flesh out those classes of constructions that intersect with the PPM working group. This could be a contribution of this draft.
