### ISSUE TITLE
Specify agg_param details

### ISSUE THREAD

**Issue by simon-friedberger** [cfrg/draft-irtf-cfrg-vdaf#82]
It should be clear what the type of agg_param is and how it should be handled.
For specific VDAFs it should probably be clarified when the agg_param needs to be available and how it is distributed.

See also ietf-wg-ppm/draft-ietf-ppm-dap/issues/267

**Comment by cjpatton** [comment]
Can you be a bit more specific? My take on https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/267 is that DAP treats the agg param as an opaque byte string, but the VDAF does not specify an encoding of this byte string.

Note that this also relates to https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/58.

**Comment by cjpatton** [comment]
Perhaps this is the misunderstanding: In DAP wherever there is a struct with a field `agg_param`, the type of that field is `opaque <0..2^16-1>`.  This is a length-prefixed byte string. There will always be here, even if it's just an empty string. For Prio3 for example, this field would simply be empty (That is, the encoding of `None` as a byte string would simply the empty string. To be clear, this is currently not specified at all.)

For some deployments the agg param may be "predictable". For Prio3 in particular, the only valid agg param is `None` (i.e., the empty string).

**Comment by simon-friedberger** [comment]
Let me see if I got this right now....

`run_vdaf` in Figure 7 uses `agg_param` in
* `prep_init`
* `prep_shares_to_prep`
* `out_shares_to_agg_share`
* `agg_shares_to_result`
but there is no statement about how `agg_param` would get distributed in a system like DAP. If some of the functions only need parts of `agg_param`, or some of them can be empty, the specific VDAF (so Chapter 7 and Chapter 8) should specify that.

1. Prio3
In Prio3 `agg_param` is empty so it's simple because it can be defined task wide in DAP and sending empty messages is the cheapest anyway.
* `task.agg_param = None`
* `CollectReq.agg_param = None`
* `AggregateInitializeReq.agg_param = None`
* `AggregateShareReq.agg_param = None`
Which conveniently makes them all the same and the same as in the VDAF.

2. Poplar1
In Poplar1 `agg_param` contains the candidate prefixes and, iiuc, needs to be provided by the DAP collector in `CollectReq.agg_param`.
So here we would end up with something like
* `task.agg_param = None`
* `CollectReq.agg_param = candidate_prefixes`
* `AggregateInitializeReq.agg_param = CollectReq.agg_param`
* `AggregateShareReq.agg_param = None`
especially, they are not all the same.

Imho, since the field in DAP is opaque this is okay, but we should clarify in DAP that the `agg_params` are not all the same.
And for the VDAF examples, we should specify how to get the different AggParams for the different steps.

**Comment by cjpatton** [comment]
* What is `task.agg_param`?
* The value of `AggregateShareReq.agg_param` is supposed to match `CollectReq.agg_param`. Does the DAP spec say otherwise?

**Comment by cjpatton** [comment]
I suspect this issue is solved in DAP by https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/282, so I will close this. @simon-friedberger, feel free to re-open if you think there is something else that needs to be done.
