### ISSUE TITLE
Can we support Prio3Aes128CountVec?

### ISSUE THREAD

**Issue by qiuxiangcassie** [cfrg/draft-irtf-cfrg-vdaf#83]
### Why
With Prio3Aes128CountVec, each measurement is a vector of integers in `[0,2)` and the aggregate is the element-wise sum. This is very helpful for supporting some use cases, e.g., checkbox survey question.

### Discussions
Based on discussions in the chat group, there are some potential concerns with the trade-off between proof generation time and proof size. 

- If the circuit has arithmetic degree 3. The proof generation will be expensive. The proof size is O(sqrt(N)).
- If the circuit has arithmetic degree 2. The proof generation is faster but the proof size is O(N)

**Comment by cjpatton** [comment]
For context, `Prio3Aes128CountVec` refers to a Prio3 variant implemented in libprio-rs.

I've added some benchmarks to libprio-rs that allow us to roughly compare these two proof systems. The latter, which has degree 2 and proof size O(N), is very similar to what's used in ENPA today. I'll call this `Prio2`. `Prio3Aeas128CountVecMultithreaded` is a variant of `Prio3Aes128CountVec` that implements the same proof system but parallelizes part of the computation. The field used for each is `Field128`.

input size: 10 (number of field elements)
| System | proof size | generation time | query time |
| ------- | ------ | ----- | ----- |
| Prio2 | 29 | 10us | 12us |
| Prio3Aes128CountVec | 28 | 21us | 15us |
| Prio3Aes128CountVecMultithreaded | 28 | 67us | 15us |

input size: 100
| System | proof size | generation time | query time |
| ------- | ------ | ----- | ----- |
| Prio2 | 231 | 76us | 58us |
| Prio3Aes128CountVec | 66 | 121us | 39us |
| Prio3Aes128CountVecMultithreaded | 66 | 146us | 37us |

input size: 1,000
| System | proof size | generation time | query time |
| ------- | ------ | ----- | ----- |
| Prio2 | 2027 | 678us | 528us |
| Prio3Aes128CountVec | 252 | 3020us | 375us |
| Prio3Aes128CountVecMultithreaded | 252 | 1001us | 366us |

input size: 10,000
| System | proof size | generation time | query time |
| ------- | ------ | ----- | ----- |
| Prio2 | 26,387 | 14.9ms | 10.7ms |
| Prio3Aes128CountVec | 582 | 21.4ms | 2.5ms |
| Prio3Aes128CountVecMultithreaded | 582 | 6.3ms | 2.5ms |

**Comment by divergentdave** [comment]
I noticed that the libprio-rs implementation of Prio3SumVec uses a floating point square root operation to compute its chunk size. To avoid interoperability headaches, I think the standardized version of this should avoid floating point operations, and instead say something like "chunk_len is the largest integer such that chunk_len squared is less than or equal to total_len". Taking the floating point square root and truncating is probably good enough for most lengths, but just in case, we could recommend starting there and iterating in an implementation note. Better that than specifying square root precision or rounding behavior.

**Comment by cjpatton** [comment]
Agreed about avoiding floating point arithmetic in the spec. In fact, we might just make `chunk_len` a parameter and RECOMMEND it be set to the square root of the input size.

**Comment by cjpatton** [comment]
Closing in favor of https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/124.
