### ISSUE TITLE
Field element encoding: Accommodations for `GF(2^255-19)`

### ISSUE THREAD

**Issue by cjpatton** [cfrg/draft-irtf-cfrg-vdaf#90]
As of #88, we'll use `GF(2^255-19)` for the leaf node field for `IdpfPoplar`. This field is a natural choice because it is close to the security level cited by [the paper](https://eprint.iacr.org/2021/017) and there are already a number of implementations of it already. (E.g., https://github.com/cloudflare/circl/tree/master/math/fp25519.) However, this choice surfaces an issue related to field element encoding that needs discussion.

First, the manner in which field elements are represented as byte strings matters for two reasons:
1. In `Prio3`, vectors of field elements are encoded and used for key derivation. In general, it's likely that the VDAF draft will have cryptographic computations that depend on encoded field elements.
2. So far we have opted to be prescriptive about the encoding of any value that would be written to the network by some application. For example, input shares and prep messages all have a fully-specified encoding. For additional discussion, see #58.

@armfazh [points out](https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/88#discussion_r899660677) that implementations of `GF(2^255-19)` typically operate directly on little-endian byte-strings (https://github.com/cloudflare/circl/blob/master/math/fp25519/fp.go#L14). The current draft uses `I2OSP()` from RFC 3447 for encoding field elements, which is big-endian. This is makes it inconvenient to use these implementations for `IdpfPoplar`, as they will be required to re-order the byte strings in order to encode them properly. This is unlikely to be a performance issue, but is potentially a source of bugs.

A related question raised by this issue is whether little-endian is somehow "better" for optimized finite field arithmetic. Perhaps using `I2OSP()` is an anti-pattern, given current trends in cryptographic code design?

Here are a few ways we might resolve this issue:

1. Keep the current big-endian encoding for all fields. In order to be compatible with the draft, an implementation of `IdpfPoplar` that uses an existing implementation of `GF(2^255-19)` may need to adjust the encoding.
2. Use little-endian for all fields. This would make it convenient to use existing implementations of `GF(2^255-19)`. Of course, this would require changing the other fields defined in the draft. However, these fields are new and there are no optimized implementations of them yet. (For what it's worth, the choice to use `I2SOP()` was somewhat arbitrary.  We noticed that it was used for other drafts, like [hash-to-curve](https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/), and it seemed like a good idea to crib on prior work.)
3. Allow each field to specify its own encoding. The potential downside here is code complexity. (It's nice when there is only one way to do a thing.)
4. If we decide not to be prescriptive about encoding (cf. #58), then this is issue is somewhat less relevant. However we would still need to specify how to encode field elements that are used as inputs to other cryptographic operations. This may or may not end up mattering for `GF(2^255-19)`.

**Comment by cjpatton** [comment]
Currently I'm inclined to take option (2.), but I would like to understand better why `I2SOP()` was designed the way it is. As it comes from [RFC 3447](https://datatracker.ietf.org/doc/html/rfc3447), we can infer that it was developed in a world in which all keys read from the wire are RSA moduli. In this world, big-endian probably seems sensible because it would allow you consume the RSA modulus from the wire one byte a time without buffering it. This is less relevant to us because we need to decode numbers whose sizes are constant (cf. `Field.ENCODED_SIZE`) and relatively small (<=32 bytes).

**Comment by armfazh** [comment]
Here are my two cents,
I think is better do not to specify any encodings, unless they are part of the _cryptographic protocol_ (and not of the communication protocol).
For example, if some element needs to be serialized because it will be an input of a hash function, then an encoding should be explicitly enforced. (here it does not matter which on is used).

Applications could be free to choose the encoding for the communication protocol. For interoperability between applications an encoding could be recommended, but not enforced.
For test vectors, an encoding could be chosen only for the test code.

**Comment by armfazh** [comment]
I2OSP seems to be omnipresent in all crypto libraries, mainly due to RSA and friends.

The little-endian seems to be relevant for Fp25519 and other optimized implementations. But in fact, optimized implementations actually represent field elements with multiple words and with redundancy, so the byte representation is not so important and it is only used at transport.

**Comment by cjpatton** [comment]
> Here are my two cents, I think is better do not to specify any encodings, unless they are part of the _cryptographic protocol_ (and not of the communication protocol). For example, if some element needs to be serialized because it will be an input of a hash function, then an encoding should be explicitly enforced. (here it does not matter which on is used).

As I mentioned at the top, in Prio3, vectors of field elements are used as input for a hash function. Thus it does matter here.

> Applications could be free to choose the encoding for the communication protocol. For interoperability between applications an encoding could be recommended, but not enforced. For test vectors, an encoding could be chosen only for the test code.

Thanks Armando, I'll put you down for (4.). I would like to hear more of your thoughts about the merits of specifying an encoding, but I think we should move that discussion to #58. I'll respond there.

**Comment by cjpatton** [comment]
Consensus from meeting today: Let's go with little endian.
